require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TelinkBleExample' do
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])
  
  pod 'RNTelinkBle', :path => '../..'
  pod 'TelinkSigMeshLib', :path => '../../TelinkSigMeshLib'
  pod 'OpenSSL-Universal'
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #  use_flipper!({ 'Flipper' => '0.80.0' })
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end
end
