export enum BleEvent {
  EVENT_MESH_NETWORK_CONNECTION = 'EVENT_MESH_NETWORK_CONNECTION',

  EVENT_UNPROVISIONED_DEVICE_FOUND = 'EVENT_UNPROVISIONED_DEVICE_FOUND',

  EVENT_SCANNING_TIMEOUT = 'EVENT_SCANNING_TIMEOUT',

  EVENT_NEW_DEVICE_ADDED = 'EVENT_NEW_DEVICE_ADDED',

  EVENT_PROVISIONING_SUCCESS = 'EVENT_PROVISIONING_SUCCESS',

  EVENT_PROVISIONING_FAILED = 'EVENT_PROVISIONING_FAILED',

  EVENT_BINDING_SUCCESS = 'EVENT_BINDING_SUCCESS',

  EVENT_BINDING_FAILED = 'EVENT_BINDING_FAILED',

  EVENT_SET_GROUP_SUCCESS = 'EVENT_SET_GROUP_SUCCESS',

  EVENT_SET_GROUP_FAILED = 'EVENT_SET_GROUP_FAILED',

  EVENT_SET_SCENE_SUCCESS = 'EVENT_SET_SCENE_SUCCESS',

  EVENT_SET_SCENE_FAILED = 'EVENT_SET_SCENE_FAILED',

  EVENT_DEVICE_STATUS = 'EVENT_DEVICE_STATUS',

  EVENT_NODE_RESET_SUCCESS = 'EVENT_NODE_RESET_SUCCESS',

  EVENT_NODE_RESET_FAILED = 'EVENT_NODE_RESET_FAILED',
}
